---
title: "export_results.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(utils)
library(tools)
library(glue)

temp_test<- tempfile(pattern ="exportscsv")
dir.create(temp_test)

fs::dir_tree(path = temp_test)
rstudioapi::filesPaneNavigate(temp_test)

df <- iris
input_path <- "exports/csv/monfichier.csv"
folder_path <- dirname(input_path)
dir.create(folder_path, recursive = TRUE)
dots <- list(col.names = FALSE, row.names = FALSE, na="na")

write.csv2(df, file = input_path)
write.csv2(df, file = input_path, col.names = c("a","b","c","d","e"), row.names=  FALSE, na = "na")

write.csv2(df, file = input_path, col.names = NA, row.names=  FALSE, na = "na")
rstudioapi::filesPaneNavigate(input_path)

check_extension = file_ext(input_path)

if(check_extension == "csv"){
  message("Le fichier créé a bien une extension .csv")
}

if(!file_exists(folder_path)){
  stop(glue("Le dossier cible \"{folder_path}\" n'existe pas."))
}
return(normalizePath(folderpath))

```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)

```

# export_results

```{r function-save_as_csv}
#' export_results Title
#'
#' @param input_path 
#' @param df A `data_frame`
#'
#' @return full_path A `string` indicating the full path of the created file.
#' @importFrom glue glue
#' @importFrom tools file_ext fileutils
#' @importFrom utils write.csv2
#' @export
#'
#' @examples
save_as_csv <- function(df, mypath,...) {


if(isFALSE(inherits(df,"data.frame"))){
  stop("df is not a data frame")
}

if(isTRUE(nrow(df) == 0)){
  stop("Le `df` fourni contient 0 lignes.")
}

dots <- list(...)  
folder_path <- dirname(mypath)
dir.create(folder_path, recursive = TRUE)
write.csv2(df, file = mypath,...)
check_extension = file_ext(mypath)

if(!check_extension == "csv"){
  stop(glue("mypath must be a csv"))
}

if(!file.exists(folder_path)){
  stop(glue("Le dossier cible \"{folder_path}\" n'existe pas."))
}
return(normalizePath(mypath))
}
```

```{r examples-export_results}
example_path <- file.path(tempfile(pattern="example_csv"), "example1.csv")
dirname(example_path)
normalizePath(example_path)
save_as_csv(iris, example_path)
extra_args <- c(col.names = FALSE, na = "NA_modified")


save_as_csv(iris, example_path, col.names = FALSE, na = "NA_modified")
```

```{r tests-export_results}

### finir les tests (mettre les expect_ etc)

test_that("save_as_csv works", {# Création d'un dossier temporaire
  
mon_dossier_temp <- tempfile(pattern = "savecsv")
dir.create(mon_dossier_temp)
normalizePath(mon_dossier_temp)

# erreur : l'extension du fichier à créer n'est pas la bonne
expect_error(
  iris |> save_as_csv(file.path(mon_dossier_temp, "output.xlsx")),
  "mypath must be a csv")

# erreur : la fonction n'est pas appliquée à un data.frame
expect_error(
  NULL |> save_as_csv(file.path(mon_dossier_temp, "output.csv")),
  "df is not a data frame")

# erreur : le chemin où doit être enregistré le fichier n'existe pas
# expect_error(
#   iris |> save_as_csv(file.path(mon_dossier_temp, "nexiste/pas/output.csv")),
#   "mypath does not exist")
#   
 })


test_that("dots are passed on as arguments", {
  
mon_dossier_temp <- tempfile(pattern = "savecsv")
dir.create(mon_dossier_temp)
export_path <- file.path(mon_dossier_temp, "output.csv")
iris |> save_as_csv(export_path, row.names = FALSE)
reimport <- read.csv(export_path, sep = ";")  


  expect_equal(ncol(reimport),
               5)
  
})

```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_export_results.Rmd", vignette_name = "Exporter ses résultats")
```

