# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand


### finir les tests (mettre les expect_ etc)

test_that("save_as_csv works", {# Création d'un dossier temporaire
  
mon_dossier_temp <- tempfile(pattern = "savecsv")
dir.create(mon_dossier_temp)
normalizePath(mon_dossier_temp)

# erreur : l'extension du fichier à créer n'est pas la bonne
expect_error(
  iris |> save_as_csv(file.path(mon_dossier_temp, "output.xlsx")),
  "mypath must be a csv")

# erreur : la fonction n'est pas appliquée à un data.frame
expect_error(
  NULL |> save_as_csv(file.path(mon_dossier_temp, "output.csv")),
  "df is not a data frame")

# erreur : le chemin où doit être enregistré le fichier n'existe pas
# expect_error(
#   iris |> save_as_csv(file.path(mon_dossier_temp, "nexiste/pas/output.csv")),
#   "mypath does not exist")
#   
 })


test_that("dots are passed on as arguments", {
  
mon_dossier_temp <- tempfile(pattern = "savecsv")
dir.create(mon_dossier_temp)
export_path <- file.path(mon_dossier_temp, "output.csv")
iris |> save_as_csv(export_path, row.names = FALSE)
reimport <- read.csv(export_path, sep = ";")  


  expect_equal(ncol(reimport),
               5)
  
})

