# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand

#' export_results Title
#'
#' @param input_path 
#' @param df A `data_frame`
#'
#' @return full_path A `string` indicating the full path of the created file.
#' @importFrom glue glue
#' @importFrom tools file_ext fileutils
#' @importFrom utils write.csv2
#' @export
#'
#' @examples
#' example_path <- file.path(tempfile(pattern="example_csv"), "example1.csv")
#' dirname(example_path)
#' normalizePath(example_path)
#' save_as_csv(iris, example_path)
#' extra_args <- c(col.names = FALSE, na = "NA_modified")
#'
#'
#' save_as_csv(iris, example_path, col.names = FALSE, na = "NA_modified")
save_as_csv <- function(df, mypath,...) {


if(isFALSE(inherits(df,"data.frame"))){
  stop("df is not a data frame")
}

if(isTRUE(nrow(df) == 0)){
  stop("Le `df` fourni contient 0 lignes.")
}

dots <- list(...)  
folder_path <- dirname(mypath)
dir.create(folder_path, recursive = TRUE)
write.csv2(df, file = mypath,...)
check_extension = file_ext(mypath)

if(!check_extension == "csv"){
  stop(glue("mypath must be a csv"))
}

if(!file.exists(folder_path)){
  stop(glue("Le dossier cible \"{folder_path}\" n'existe pas."))
}
return(normalizePath(mypath))
}
